### PR TITLE
Fix URL for Australia, updated requirements file dependency versions

### PR DESCRIPTION
**Pull request by MKSG-MugunthKumar**
Hey,
The URL for audible australia was wrong, and I was getting errors. Here is a fix.
Alongside, I updated the dependencies to the latest as well.

### CODE REVIEW

**Comment by gostak-dd** [comment]
Thanks for the URL fix. Any reasons for updating the dependencies?

**Comment by MKSG-MugunthKumar** [comment]
They were erroring out on latest Python on Mac—MugunthOn 20 Jul 2024, at 3:52 am, Gustaf ***@***.***> wrote:﻿
Thanks for the URL fix. Any reasons for updating the dependencies?

**Comment by gostak-dd** [comment]
Which Python version exactly? And can you confirm the CLI fully works with the updated dependencies? I don't subscribe to Audible otherwise I'd do it myself

**Comment by MKSG-MugunthKumar** [comment]
I'm on Python 3.12.4, Mac binary, and yes, the updated dependencies work. However, I do not have a Windows/Linux environment.

I can send a new PR with just the URL changes if you like.

The URL changes are working. With audible.co.au, even the home page doesn't load.

 wrote:

**Comment by gostak-dd** [comment]
Ok that is a later version than I have tested on, so I will approve.

Like I said, I don't subscribe to Audible anymore, are you available to co-maintain the project? I will still be on board for minor fixes like these, but it would be good to have someone who can test out the actual Audible account stuff.

**Comment by MKSG-MugunthKumar** [comment]
Yes, I can help over my weekends. I wanted to implement a feature where the extracted text could be pushed to Readwise. Is this something you are interested? If yes, I can get it done and send you another PR.—MugunthOn 24 Jul 2024, at 3:35 am, Gustaf ***@***.***> wrote:﻿
Ok that is a later version than I have tested on, so I will approve.
Like I said, I don't subscribe to Audible anymore, are you available to co-maintain the project? I will still be on board for minor fixes like these, but it would be good to have someone who can test out the actual Audible account stuff.

**Comment by gostak-dd** [comment]
Yes this would be great! I had the idea too a while back but I stuck with just using the export to csv for Anki and Notion. Let me know if you get stuck anywhere in the code.

**Comment by gostak-dd** [comment]
just make a file called readwise.py and put the logic there and have main_file.py import it as a module

**Pull request merged**
